---
- name: Update Linux Kernel
  hosts: all
  become: yes
  tasks:
    - name: Show kernel version
      command: uname -r
      register: kernel_version


    - name: Display Linux Kernel Version
      debug:
        msg: "The Linux kernel version is {{ kernel_version.stdout }}"


    - name: Update Ubuntu kernel
      apt:
        name: linux-image-generic
        state: latest
      when: ansible_distribution == 'Ubuntu'


    - name: Update Amazon Linux kernel
      dnf:
        name: kernel
        state: latest
      when: ansible_distribution == 'Amazon'